# Generated by Django 4.1.4 on 2024-04-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_category_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
